---
name: Catalyst-Plugin-FormValidator-Simple-Auto
version: 0.08
author:
  - 'Daisuke Murase <typester@cpan.org>'
abstract: Smart validation with FormValidator::Simple
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.30
  Catalyst::Plugin::FormValidator::Simple: 0
  UNIVERSAL::isa: 0
  YAML: 0
build_requires:
  HTTP::Request::Common: 0
provides:
  Catalyst::Plugin::FormValidator::Simple::Auto:
    file: lib/Catalyst/Plugin/FormValidator/Simple/Auto.pm
    version: 0.08
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
