abstract: Smart validation with FormValidator::Simple
author: Daisuke Murase <typester@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-FormValidator-Simple-Auto
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.30
  Catalyst::Plugin::FormValidator::Simple: 0
  UNIVERSAL::isa: 0
  YAML: 0
version: 0.09_01
